include: package:flutter_lints/flutter.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    dead_code: error
    deprecated_member_use: error
    always_declare_return_types: error
    always_put_control_body_on_new_line: error
    always_use_package_imports: error
    annotate_overrides: error
    avoid_as: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: error
    avoid_empty_else: error
    avoid_final_parameters: error
    avoid_init_to_null: error
    avoid_multiple_declarations_per_line: error
    avoid_renaming_method_parameters: error
    avoid_returning_null_for_void: error
    avoid_unnecessary_containers: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    camel_case_extensions: error
    cancel_subscriptions: error
    close_sinks: error
    constant_identifier_names: error
    empty_catches: error
    empty_constructor_bodies: error
    file_names: error
    matching_super_parameters: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    no_leading_underscores_for_local_identifiers: error
    no_literal_bool_comparisons: error
    no_logic_in_create_state: error
    no_self_assignments: error
    non_constant_identifier_names: error
    null_check_on_nullable_type_parameter: error
    prefer_adjacent_string_concatenation: error
    prefer_const_constructors: error
    prefer_const_declarations: error
    prefer_final_fields: error
    prefer_final_locals: error
    prefer_interpolation_to_compose_strings: error
    recursive_getters: error
    sized_box_for_whitespace: error
    sized_box_shrink_expand: error
    sort_child_properties_last: error
    type_annotate_public_apis: error
    type_init_formals: error
    unnecessary_await_in_return: error
    unnecessary_brace_in_string_interps: error
    unnecessary_late: error
    unnecessary_new: error
    unnecessary_null_checks: error
    unnecessary_nullable_for_final_variable_declarations: error
    unnecessary_raw_strings: error
    unnecessary_string_interpolations: error
    unnecessary_this: error
    unreachable_from_main: error
    use_build_context_synchronously: error
    use_colored_box: error
    use_decorated_box: error
    use_full_hex_values_for_flutter_colors: error
    use_if_null_to_convert_nulls_to_bools: error
    use_key_in_widget_constructors: error
    use_rethrow_when_possible: error
    use_super_parameters: error
    valid_regexps: error
    unused_local_variable: error
    unused_import: error
linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - annotate_overrides
    - avoid_as
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_empty_else
    - avoid_final_parameters
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - camel_case_extensions
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - matching_super_parameters
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_leading_underscores_for_local_identifiers
    - no_literal_bool_comparisons
    - no_logic_in_create_state
    - no_self_assignments
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - prefer_adjacent_string_concatenation
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - recursive_getters
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - sort_child_properties_last
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_raw_strings
    - unnecessary_string_interpolations
    - unnecessary_this
    - unreachable_from_main
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_if_null_to_convert_nulls_to_bools
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_super_parameters
    - valid_regexps